/*
   Include in output:

   This file is part of Natural Docs, which is Copyright © 2003-2011 Greg Valure.
   Natural Docs is licensed under version 3 of the GNU Affero General Public
   License (AGPL).  Refer to License.txt for the complete details.

   This file may be distributed with documentation files generated by Natural Docs.
   Such documentation is not covered by Natural Docs' copyright and licensing,
   and may have its own copyright and distribution terms as decided by its author.

*/


/* Class: NDPageFrame
	 _____________________________________________________________________________

*/
var NDPageFrame = { };


/* Function: OnLoad
*/
NDPageFrame.OnLoad = function ()
	{
	if (navigator.userAgent.indexOf("MSIE 6") != -1)
		{
		// IE 6 doesn't like fixed positioning the way other browsers do.

		document.getElementsByTagName("html")[0].style.overflow = "hidden";  

		document.getElementById("NDHeader").style.position = "absolute";
		document.getElementById("NDFooter").style.position = "absolute";
		document.getElementById("NDMenu").style.position = "absolute";
		document.getElementById("NDContent").style.position = "absolute";
		}

	this.OnResize();
	window.onresize = this.OnResize;
	};

/* Function: OnResize
*/
NDPageFrame.OnResize = function ()
	{
	var width = NDCore.WindowClientWidth();
	var height = NDCore.WindowClientHeight();

	var header = document.getElementById("NDHeader");
	var footer = document.getElementById("NDFooter");
	var menu = document.getElementById("NDMenu");
	var content = document.getElementById("NDContent");

	NDCore.SetToAbsolutePosition(header, 0, 0, width, undefined);
	NDCore.SetToAbsolutePosition(footer, 0, undefined, width, undefined);

	var headerHeight = header.offsetHeight;
	var footerHeight = footer.offsetHeight;

	// Need separate calls to set the Y position and width since wrapping may change the height.
	NDCore.SetToAbsolutePosition(footer, undefined, height - footerHeight, undefined, undefined);

	var menuWidth = Math.round(width / 3);

	NDCore.SetToAbsolutePosition(menu, 0, headerHeight, menuWidth, height - headerHeight - footerHeight);
	NDCore.SetToAbsolutePosition(content, menuWidth, headerHeight, width - menuWidth, height - headerHeight - footerHeight);

	content.innerHTML = 
		"Page Width: " + width + "<br>" +
		"header Width (style): " + header.style.width + "<br>" +
		"<b>header Width (offsetWidth): " + header.offsetWidth + "</b><br>" +
		"header Width (clientWidth): " + header.clientWidth + "<br>" +
		"header Width (scrollWidth): " + header.scrollWidth + "<br>";

	};