/*
	Include in output:

	This file is part of Natural Docs, which is Copyright © 2003-2011 Greg Valure.
	Natural Docs is licensed under version 3 of the GNU Affero General Public
	License (AGPL).  Refer to License.txt for the complete details.

	This file may be distributed with documentation files generated by Natural Docs.
	Such documentation is not covered by Natural Docs' copyright and licensing,
	and may have its own copyright and distribution terms as decided by its author.
*/

"use strict";


/* Class: NDSummary
	___________________________________________________________________________

*/
var NDSummary = new function ()
	{ 

	// Group: Functions
	// ________________________________________________________________________


	/* Function: Start
	*/
	this.Start = function ()
		{
		};


	/* Function: GoToFileHashPath
		Changes the current summary to the passed hash string, such as "File2:folder/folder/file.cs".
	*/
	this.GoToFileHashPath = function (hashPath)
		{
		// This code is very simple because we're only loading the metadata to cause the page title change
		// for now.

		var head = document.getElementsByTagName("head")[0];

		// Remove the previous loader if there was one.
		var loader = document.getElementById("NDMetaDataLoader");

		if (loader)
			{  head.removeChild(loader);  }

		// Create a new one.

		var script = document.createElement("script");
		script.src = NDCore.FileHashPathToMetaDataPath(hashPath);
		script.type = "text/javascript";
		script.id = "NDMetaDataLoader";

		head.appendChild(script);
		};


	};
